//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class alaplap_usb
    {
        public int id { get; set; }
        public Nullable<int> alaplap_id { get; set; }
        public Nullable<int> usb_tipus_id { get; set; }
        public int darab { get; set; }
    
        public virtual alaplap alaplap { get; set; }
        public virtual usb_tipus usb_tipus { get; set; }
    }
}
