//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpu
    {
        public int id { get; set; }
        public int alkatresz_gyarto_id { get; set; }
        public string megnevezes { get; set; }
        public int magok_darab { get; set; }
        public decimal frekvencia { get; set; }
        public int frekvencia_mertekegyseg_id { get; set; }
        public Nullable<int> proc_foglalat_tipus_id { get; set; }
        public Nullable<int> kep_id { get; set; }
        public decimal netto_ar { get; set; }
    
        public virtual alkatresz_gyarto alkatresz_gyarto { get; set; }
        public virtual cpu_frekvencia_mertekegyseg cpu_frekvencia_mertekegyseg { get; set; }
        public virtual kepek kepek { get; set; }
        public virtual proc_foglalat_tipus proc_foglalat_tipus { get; set; }
    }
}
