//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStore.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerStoreEntities : DbContext
    {
        public ComputerStoreEntities()
            : base("name=ComputerStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alaplap> alaplap { get; set; }
        public virtual DbSet<billentyuzet> billentyuzet { get; set; }
        public virtual DbSet<cpu> cpu { get; set; }
        public virtual DbSet<eger> eger { get; set; }
        public virtual DbSet<hattertar> hattertar { get; set; }
        public virtual DbSet<memoria> memoria { get; set; }
        public virtual DbSet<monitor> monitor { get; set; }
        public virtual DbSet<szamitogep_haz> szamitogep_haz { get; set; }
        public virtual DbSet<tapegyseg> tapegyseg { get; set; }
        public virtual DbSet<videokartya> videokartya { get; set; }
        public virtual DbSet<alaplap_hattertar> alaplap_hattertar { get; set; }
        public virtual DbSet<alaplap_usb> alaplap_usb { get; set; }
        public virtual DbSet<alkatresz_gyarto> alkatresz_gyarto { get; set; }
        public virtual DbSet<cpu_frekvencia_mertekegyseg> cpu_frekvencia_mertekegyseg { get; set; }
        public virtual DbSet<hattertar_tipus> hattertar_tipus { get; set; }
        public virtual DbSet<hattertarolo_csatolo_tipus> hattertarolo_csatolo_tipus { get; set; }
        public virtual DbSet<kepek> kepek { get; set; }
        public virtual DbSet<memoria_foglalat_tipus> memoria_foglalat_tipus { get; set; }
        public virtual DbSet<monitor_csatolo> monitor_csatolo { get; set; }
        public virtual DbSet<monitor_felbontas> monitor_felbontas { get; set; }
        public virtual DbSet<monitor_meret> monitor_meret { get; set; }
        public virtual DbSet<pci_express_tipus> pci_express_tipus { get; set; }
        public virtual DbSet<proc_foglalat_tipus> proc_foglalat_tipus { get; set; }
        public virtual DbSet<usb_tipus> usb_tipus { get; set; }
        public virtual DbSet<vga_csatolo_felulet_tipus> vga_csatolo_felulet_tipus { get; set; }
        public virtual DbSet<videokartya_monitor> videokartya_monitor { get; set; }
    }
}
