//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class videokartya_monitor
    {
        public int id { get; set; }
        public int videokartya_id { get; set; }
        public int monitor_csatolo_id { get; set; }
        public int darab { get; set; }
    
        public virtual videokartya videokartya { get; set; }
        public virtual monitor_csatolo monitor_csatolo { get; set; }
    }
}
